config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#top_benefits'

  match '/office-managers', to: 'static_pages#top_benefits_connecting', via: 'get', as: :top_benefits_connecting
  match '/business-owner', to: 'static_pages#top_benefits_growing', via: 'get', as: :top_benefits_growing
  match '/customers', to: 'static_pages#top_benefits_rewarding', via: 'get', as: :top_benefits_rewarding
  match '/who-we-are', to: 'static_pages#about', via: 'get', as: :about
  match '/team', to: 'static_pages#about_team', via: 'get', as: :about_team
  match '/idea', to: 'static_pages#about_idea', via: 'get', as: :about_idea
  match '/partners', to: 'static_pages#partners', via: 'get', as: :partners
  match '/contact', to: 'static_pages#contact', via: 'get', as: :contact
  match '/connect-with-us', to: 'static_pages#support', via: 'get', as: :support
  match '/schedule-a-call', to: 'static_pages#support_schedule', via: 'get', as: :support_schedule
  match '/appreciado-support', to: 'static_pages#support_appreciado', via: 'get', as: :support_appreciado
  match '/question-support', to: 'static_pages#support_question', via: 'get', as: :support_question
  match '/purchase', to: 'static_pages#purchase', via: 'get', as: :purchase
  match '/thank-you', to: 'static_pages#thankyou', via: 'get', as: :thankyou
  match '/privacy', to: 'static_pages#privacy', via: 'get', as: :privacy
  match '/terms-conditions', to: 'static_pages#terms', via: 'get', as: :terms

  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        
         ContactMailer.welcome_email(@contact).deliver
         ContactMailer.query_mail(@contact).deliver

        format.html { redirect_to :back }
        #flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
        format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  
     def contact_params
      params.require(:contact).permit(:radio_option, :fname, :lname, :email, :phone, :message)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top_benefits
  end

  def top_benefits_connecting    
  end

  def top_benefits_growing    
  end

  def top_benefits_rewarding    
  end

  def about
  end

  def about_team
  end

  def about_idea
  end

  def partners
  end

  def contact
  end

  def support
    @contact = Contact.new
  end

  def support_schedule    
  end

  def support_appreciado    
  end

  def support_question    
  end

  def purchase
  end

  def thankyou    
  end

  def privacy    
  end

  def terms    
  end

  def demo
    render :layout => 'demo'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Appreciado</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= favicon_link_tag 'favicon.png' %>
  <!-- core CSS -->
    <link href="/assets/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/font-awesome.min.css" rel="stylesheet">
    <link href="/assets/animate.min.css" rel="stylesheet">
    <link href="/assets/owl.carousel.css" rel="stylesheet">
    <link href="/assets/owl.transitions.css" rel="stylesheet">
    <link href="/assets/prettyPhoto.css" rel="stylesheet">
    <%= yield :datepicker_css %>
    <link href="/assets/main.css" rel="stylesheet">
    <link href="/assets/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <!-- <link rel="shortcut icon" href="/assets/ico/favicon.ico"> -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/assets/ico/apple-touch-icon-57-precomposed.png">
  
  <%= csrf_meta_tags %>
  
    <%= yield :benefits_modal %>
    <%= yield :about_testi %>
</head>
<body <%= yield :index_body %>>
<div class="text-right top-header bk-color-blue">
<!-- <%= link_to "LOGIN", root_path, method: :get %>  &nbsp;&nbsp;-->
<a data-toggle="tooltip" data-placement="bottom" data-html="true" title="PROUDLY<br>CANADIAN" rel="tooltip"><img src="/assets/canada-flag.png" alt="Canada Flag"></a>
</div>
<!-- <div class="text-center">
    <%= link_to(image_tag("logo.png", alt: "Appreciado Logo"), root_path, method: :get) %>
</div> -->
<header id="header">
    <nav id="main-menu" class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
            <%= link_to(image_tag("appreciadologo.png", alt: "Appreciado"), root_path, method: :get, class: "hidden-sm hidden-md hidden-lg") %> 
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
                        </div>
                    </div>
                </div>
            </div>
    
            <div class="collapse navbar-collapse">

                <ul class="nav navbar-nav">
                     <%= link_to(image_tag("appreciadologo.png", alt: "Appreciado"), root_path, method: :get, class: "hidden-xs") %>
                      
                    <li class="<%= 'active' if current_page?(top_benefits_connecting_path) %>"><%= link_to "OFFICE MANAGERS", top_benefits_connecting_path, :method => :get %></li>
                    <li class="<%= 'active' if current_page?(top_benefits_growing_path) %>"><%= link_to "BUSINESS OWNERS", top_benefits_growing_path, :method => :get %></li>
                    <li class="<%= 'active' if current_page?(top_benefits_rewarding_path) %>"><%= link_to "CUSTOMERS", top_benefits_rewarding_path, :method => :get %></li>
                    <li class="<%= 'active' if current_page?(about_path)||current_page?(about_team_path) %>"><%= link_to "WHO WE ARE", about_path, :method => :get %></li>
                    <!--<li><%= link_to "BLOG", "http://blog.appreciado.com/", target: "_blank", :method => :get %></li>-->
                    <li class="<%= 'active' if current_page?(support_path)||current_page?(support_appreciado_path)||current_page?(support_schedule_path) %>"><%= link_to "CONNECT WITH US", support_path, :method => :get %></li>
                      
                    <!--<li class="<%= 'active' if current_page?(support_question_path) %>"><%= link_to "FAQ", support_question_path, :method => :get %></li>-->
                    <!--<li class="<%= 'active' if current_page?(purchase_path) %>"><%= link_to "PURCHASE", purchase_path, :method => :get %></li>-->
                </ul>
            </div>
        </div><!--/.container-->
    </nav><!--/nav-->
</header><!--/header-->
<%= yield %>
<footer id="footer">
    <div class="container">
        <!-- <div class="row">
            <div class="col-sm-12 text-center pad-bot3">
        <button class="btn-chat"><i class="fa fa-weixin"></i> CHAT ONLINE</button>
            </div>
        </div> -->
        <div class="row">
            <div class="col-sm-12 pad-top1 text-center">
                <address>
                    <!-- <h3>CONTACT US</h3> -->
                    <p>OFFICE <a href="tel:+15873182526">+1 587-318-2526 </a> <br>
                       <a href="mailto:hello@appreciado.com?Subject=Hello%20Appreciado">HELLO@APPRECIADO.COM</a></p>
                </address>
            </div>
            <div class="col-md-4 text-center">
                <!-- <address>
                    <h3>FOLLOW US</h3>
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook-square fa-3x"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter-square fa-3x"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin-square fa-3x"></i></a></li>
                    </ul>
                </address> -->
            </div>
            <!--<div class="col-md-4">-->
                <!--<address>-->
                    <!--&lt;!&ndash; <h3>LOCATION</h3> &ndash;&gt;-->
                    <!--<p>317 7 Ave SW, Calgary, AB T2P 1B5 <br>-->
                       <!--<a href="https://www.google.com/maps/place/317+7+St+SW,+Calgary,+AB+T2P,+Canada/@51.0501008,-114.0785038,17z/data=!3m1!4b1!4m2!3m1!1s0x53716fe50c4e8f55:0xc63abf0afbd87bd0?hl=en-US" target="_blank"><i class="fa fa-map-marker"></i> VIEW MAP</a></p>-->
                <!--</address>-->
            <!--</div>-->
            <div class="col-sm-12 pad-top1 text-center" id="footer-bot">
                <ul>
                    <li><%= link_to "WHO WE ARE", about_path, :method => :get %></li>
                    <li><%= link_to "PRIVACY", privacy_path, :method => :get %></li>
                    <li><%= link_to "TERMS & CONDITIONS", terms_path, :method => :get %></li>
                    <li><%= link_to "CONNECT WITH US", support_path, :method => :get %></li>
                </ul>
            </div>
            
        </div>
    </div>
</footer>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="/assets/bootstrap.min.js"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="/assets/owl.carousel.min.js"></script>
    <script src="/assets/mousescroll.js"></script>
    <script src="/assets/smoothscroll.js"></script>
    <script src="/assets/jquery.prettyPhoto.js"></script>
    <script src="/assets/jquery.isotope.min.js"></script>
    <script src="/assets/jquery.inview.min.js"></script>
    <script src="/assets/wow.min.js"></script>
    <script src="/assets/main.js"></script>

    <script type="text/javascript">
        $(function () {
            $("[rel='tooltip']").tooltip();
        });
        $(document).ready(function(){
            var submitted = getUrlVars()["submitted"];
            if(submitted==1)
            {
                $('#message').removeClass('hidden');
            }
        });
        function getUrlVars()
        {
            var vars = [], hash;
            var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
            for(var i = 0; i < hashes.length; i++)
            {
                hash = hashes[i].split('=');
                vars.push(hash[0]);
                vars[hash[0]] = hash[1];
            }
            return vars;
        }
    </script>
    
    <script type="text/javascript">
    $('.dropdown').hover(function() {
      $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeIn(500);
    }, function() {
      $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeOut(500);
    });
    </script>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-62638308-1', 'auto');
        ga('send', 'pageview');

    </script>
    
    <%= yield :faq_js %>
    <%= yield :modal_js %>
    <%= yield :team_js %>

</body>
</html>

app/views/layouts/demo.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Appreciado</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= favicon_link_tag 'favicon.png' %>
  <!-- core CSS -->
    <link href="/assets/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/font-awesome.min.css" rel="stylesheet">
    <link href="/assets/animate.min.css" rel="stylesheet">
    <link href="/assets/owl.carousel.css" rel="stylesheet">
    <link href="/assets/owl.transitions.css" rel="stylesheet">
    <link href="/assets/prettyPhoto.css" rel="stylesheet">
    <%= yield :datepicker_css %>
    <link href="/assets/main.css" rel="stylesheet">
    <link href="/assets/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <!-- <link rel="shortcut icon" href="/assets/ico/favicon.ico"> -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/assets/ico/apple-touch-icon-57-precomposed.png">
  
  <%= csrf_meta_tags %>
  
</head>
<body>


<%= yield %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="/assets/bootstrap.min.js"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="/assets/owl.carousel.min.js"></script>
    <script src="/assets/mousescroll.js"></script>
    <script src="/assets/smoothscroll.js"></script>
    <script src="/assets/jquery.prettyPhoto.js"></script>
    <script src="/assets/jquery.isotope.min.js"></script>
    <script src="/assets/jquery.inview.min.js"></script>
    <script src="/assets/wow.min.js"></script>
    <script src="/assets/main.js"></script>    
    
</body>
</html>

app/views/static_pages/about.html.erb
<%= content_for :about_testi do %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<script type="text/javascript">
$(document).ready(function(){
    /* Get iframe src attribute value i.e. YouTube video url
    and store it in a variable */
    var url = $("#CoryLiss").attr('src');
    
    /* Assign empty url value to the iframe src attribute when
    modal hide, which stop the video playing */
    $("#myModalCoryLiss").on('hide.bs.modal', function(){
        $("#CoryLiss").attr('src', '');
    });
    
    /* Assign the initially stored url back to the iframe src
    attribute when modal is displayed again */
    $("#myModalCoryLiss").on('show.bs.modal', function(){
        $("#CoryLiss").attr('src', url);
    });
});
</script>

<script type="text/javascript">
$(document).ready(function(){
    var url = $("#NadiaNizam").attr('src');
    
    $("#myModalNadiaNizam").on('hide.bs.modal', function(){
        $("#NadiaNizam").attr('src', '');
    });
    
    $("#myModalNadiaNizam").on('show.bs.modal', function(){
        $("#NadiaNizam").attr('src', url);
    });
});
</script>

<script type="text/javascript">
$(document).ready(function(){
    var url = $("#GlennChan").attr('src');
    
    $("#myModalGlennChan").on('hide.bs.modal', function(){
        $("#GlennChan").attr('src', '');
    });
    
    $("#myModalGlennChan").on('show.bs.modal', function(){
        $("#GlennChan").attr('src', url);
    });
});
</script>

<script type="text/javascript">
$(document).ready(function(){
    var url = $("#MiteGiuffre").attr('src');
    
    $("#myModalMiteGiuffre").on('hide.bs.modal', function(){
        $("#MiteGiuffre").attr('src', '');
    });
    
    $("#myModalMiteGiuffre").on('show.bs.modal', function(){
        $("#MiteGiuffre").attr('src', url);
    });
});
</script>

<script type="text/javascript">
$(document).ready(function(){
    var url = $("#HowItWorksBottom").attr('src');
    
    $("#myModalHowItWorksBottom").on('hide.bs.modal', function(){
        $("#HowItWorksBottom").attr('src', '');
    });
    
    $("#myModalHowItWorksBottom").on('show.bs.modal', function(){
        $("#HowItWorksBottom").attr('src', url);
    });
});
</script>

<% end %>   

<%= content_for :index_body do %>id="home" class="homepage"<% end %>    

<section id="top-top">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h1>WHO WE ARE</h1>
            </div>
        </div>
    </div>
</section>

<section id="about-mid1"> 
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <div class="row text-center bk-color-sky pad-top4 min-h650">
                        <div class= "hidden-xs">
                            <%= link_to("<h1>THE IDEA</h1> #{image_tag("whoarewe/icon-idea.png", alt: "Idea")}".html_safe, about_idea_path, method: :get) %>
                            <h3>Appreciado believes in thoughtfully growing heartfelt connections!</h3>
                        </div>
                        <div class= "hidden-sm hidden-md hidden-lg">
                            <%= link_to("<h1>THE IDEA</h1> #{image_tag("whoarewe/icon-idea-r.png", alt: "Idea")}".html_safe, about_idea_path, method: :get) %>
                            <h3>Appreciado believes in thoughtfully, growing, heartfelt connections! Appreciado is a mobile platform that will revolutionize how dental practices interact with patients. We believe in connecting, rewarding + growing. </h3>
                        </div>
                        
                </div>        
            </div>     
            <div class="col-sm-6">                
                <div class="row text-center bk-color-blue-green pad-top4 min-h650">
                        <div class= "hidden-xs">
                         <%= link_to("<h1>THE TEAM</h1> #{image_tag("whoarewe/icon-team.png", alt: "Team")}".html_safe, about_team_path, method: :get) %>
                         <h3>We are a collective of mom's and dad's who care about making the world a better place through technology and increasing the amount of gratitude on the planet.</h3>
                        </div>
                        <div class= "hidden-sm hidden-md hidden-lg">
                        <%= link_to("<h1>THE TEAM</h1> #{image_tag("whoarewe/icon-team-r.png", alt: "Team")}".html_safe, about_team_path, method: :get) %>
                        <!-- <a href="/team"><h1>THE TEAM</h1>
                        <img src="/assets/whoarewe/icon-team.png"></a> -->
                        <h3>We are a collective of mom's and dad's who care about making the world a better place through technology and increasing the amount of gratitude on the planet.</h3>
                        </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="about-mid2">
    <div class="container hidden">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h1><i class="fa fa-twitter"></i><a href="https://twitter.com/intent/tweet?button_hashtag=STANDFORAPPRECIATION"><u>#STANDFORAPPRECIATION</u></a></h1>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
            </div>
        </div>
    </div>
</section>

<section id="about-mid3 hidden">
    <div class="container hidden">
        <div class="row">
            <div class="col-sm-12 col-lg-11 text-right" >
                <ul>
                <li class="dropdown">
                   <%= link_to("<p class='invisible help'></p>".html_safe, "http://blog.appreciado.com/","data-toggle" => "dropdown", target: "_blank", method: :get) %>
                    <ul class="dropdown-menu">
                        <li>
                            <img src="/assets/whoarewe/helping-u.png">
                        </li>    
                    </ul>
                </li>
                </ul>
            </div>
        </div>
    </div>
</section>

<!-- <section id="about-mid4">
    <div class="bk-color-gray">
        <div class="container">                
            <div class="row text-center pad-top1">
                <div class="col-sm-12">
                    <h1>TESTIMONIALS</h1>
                </div>
            </div>
            <div class="row text-center modal-sky pad-top2 pad-bot1">
                <div class="col-md-3">
                    <div class="bs-example"> 
                        <a href="#myModalCoryLiss" data-toggle="modal">
                        <img alt="Cory Liss" src="/assets/whoarewe/Dr-Cory.jpg" class="img-circle" />
                        <h4>Dr. Cory Liss</h4></a>
                        
                        <div id="myModalCoryLiss" class="modal fade">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close fa-4x" data-dismiss="modal" aria-hidden="true">×</button>
                                        <h2 class="modal-title">Dr. Cory Liss</h2>
                                    </div>
                                    <div class="modal-body">
                                        <iframe id="CoryLiss" width="560" height="315" src="//www.youtube.com/embed/YE7VzlLtp-4" frameborder="0" allowfullscreen></iframe>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="bs-example"> 
                        <a href="#myModalNadiaNizam" data-toggle="modal">
                        <img alt="Nadia Nizam" src="/assets/whoarewe/Dr-Nadia.jpg" class="img-circle" />
                        <h4>Dr. Nadia Nizam</h4></a>                        
                        <div id="myModalNadiaNizam" class="modal fade">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close fa-4x" data-dismiss="modal" aria-hidden="true">×</button>
                                        <h2 class="modal-title">Dr. Nadia Nizam</h2>
                                    </div>
                                    <div class="modal-body">
                                        <iframe id="NadiaNizam" width="560" height="315" src="https://www.youtube.com/embed/Nci9e1lHtwY" frameborder="0" allowfullscreen></iframe>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>                    
                </div>
                <div class="col-md-3">
                    <div class="bs-example"> 
                        <a href="#myModalGlennChan" data-toggle="modal">
                        <img alt="Glenn Chan" src="/assets/whoarewe/Dr-Glenn.jpg" class="img-circle" />
                        <h4>Dr. Glenn Chan</h4></a>                        
                        <div id="myModalGlennChan" class="modal fade">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close fa-4x" data-dismiss="modal" aria-hidden="true">×</button>
                                        <h2 class="modal-title">Dr. Glenn Chan</h2>
                                    </div>
                                    <div class="modal-body">
                                        <iframe id="GlennChan" width="560" height="315" src="//www.youtube.com/embed/YE7VzlLtp-4" frameborder="0" allowfullscreen></iframe>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="bs-example"> 
                        <a href="#myModalMiteGiuffre" data-toggle="modal">
                        <img alt="Mite Giuffre" src="/assets/whoarewe/Dr-Mite.jpg" class="img-circle" />
                        <h4>Dr. Mite Giuffre</h4></a>                        
                        <div id="myModalMiteGiuffre" class="modal fade">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close fa-4x" data-dismiss="modal" aria-hidden="true">×</button>
                                        <h2 class="modal-title">Dr. Mite Giuffre</h2>
                                    </div>
                                    <div class="modal-body">
                                        <iframe id="MiteGiuffre" width="560" height="315" src="https://www.youtube.com/embed/Nci9e1lHtwY" frameborder="0" allowfullscreen></iframe>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section> -->


<section class="hidden">
    <div class="container hidden">
        <div class="row">
            <div class="col-sm-12 text-center btn3-mar btn-pad">
                <button type="button" class="btn-pink" href="#myModalHowItWorksBottom" data-toggle="modal">"HOW IT WORKS"<br>VIDEO</button>
                <button type="button" class="btn-blue">PURCHASE<br>APPRECIADO</button>
                <%= link_to "CONNECT<br>WITH US".html_safe, support_path, class: "btn-green", :method => :get %>
            </div>
        </div>
    </div>    
</section>

                <!-- How It Works Video Bottom -->
                <div class="text-center modal-sky pad-top2 pad-bot1 hidden">
                    <div class="bs-example">                         
                        <div id="myModalHowItWorksBottom" class="modal fade">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close fa-4x" data-dismiss="modal" aria-hidden="true">×</button>
                                        <h2 class="modal-title">How It Works</h2>
                                    </div>
                                    <div class="modal-body">
                                        <iframe id="MiteGiuffre" width="560" height="315" src="https://www.youtube.com/embed/Nci9e1lHtwY" frameborder="0" allowfullscreen></iframe>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

    

app/views/static_pages/demo.html.erb
<section id="demo" class="hidden-xs">
    <div class="container">
        <div class="row">            
            <div class="col-sm-12">
            </div>
        </div>
    </div>
</section>

<!--<section id="demo1" class="hidden-sm hiddem-md hidden-lg">-->
    <!--<div class="container">-->
        <!--<div class="row">            -->
            <!--<div class="col-sm-12">-->
                <!---->
            <!--</div>-->
        <!--</div>-->
    <!--</div>-->
<!--</section>-->
<section id="demo2" class="hidden-sm hiddem-md hidden-lg">
  <div id="demo3" class="container centered-logo">
    <div id="demo4" class="row centered-logo">
      <div class="col-sm-12">

      </div>
    </div>
  </div>
</section>